apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-nodejs-develop
  namespace: kubernetes-cluster-visheshjindal
  labels:
    app: nagp-nodejs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nagp-nodejs
  template:
    metadata:
      labels:
        app: nagp-nodejs
    spec:
      containers:
        - name: nagp-nodejs
          image: visheshjindal/i-visheshjindal-develop:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3010  
          envFrom:
            - configMapRef:
                name: special-config
            - secretRef:
                name: special-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: kubernetes-cluster-visheshjindal  
data:
  VARTYPECM: CONFIGMAP
  TYPECM: NODE-JS
---
apiVersion: v1
kind: Secret
metadata:
  name: special-secret
  namespace: kubernetes-cluster-visheshjindal
data:
  VARTYPE: U0VDUkVU
  TYPE: U2VjcmV0VGV4dA==
              