apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-nodejs-main
  labels:
    app: nagp-nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nagp-nodejs
  template:
    metadata:
      labels:
        app: nagp-nodejs
    spec:
      containers:
        - name: nagp-nodejs
          image: visheshjindal/i-visheshjindal-main:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3011
          envFrom:
            - configMapRef:
                name: special-config
            - secretRef:
                name: special-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config  
data:
  VARTYPE: CONFIGMAP
  TYPE: NODE-JS
---
apiVersion: v1
kind: Secret
metadata:
  name: special-secret
data:
  VARTYPE: CONFIGMAP
  TYPE: NODE-JS
    