apiVersion: v1
kind: Service
metadata:
  name: nagp-services
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: nagp-services
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3010
  - name: http2
    port: 81
    protocol: TCP
    targetPort: 3011
  selector:
    app: nagp
  sessionAffinity: None